### ISSUE TITLE
Mark all math of inlining

### ISSUE THREAD

**Issue by dzmitry-lahoda** [codeandcats/KdTree#18]
Hi,

I have used https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions AggressiveInlining 
 and mark my generic math classes like your. Seems this makes in .NET Core to be zero cost.
At least this attribute makes that more likely. May be measure.

Thanks

**Comment by codeandcats** [comment]
Thanks! 🙂
