### ISSUE TITLE
Inserted values are ignored if inserted with the same key

### ISSUE THREAD

**Issue by ForNeVeR** [codeandcats/KdTree#5]
KdTree seems to always be ignoring the new values if there's an old value stored with the same key. Here's an example:

```csharp
using System;
using KdTree;
using KdTree.Math;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            var tree = new KdTree<float, int>(2, new FloatMath());
            var coords = new[] { 0.0f, 0.0f };
            tree.Add(coords, 100);
            tree.Add(coords, 200);

            var z = tree.FindValueAt(coords);
            Console.Write(z); // => 100, but I'd expect 200
        }
    }
}
```

It would be better to either replace the existing value or throw an exception. I think that the library should never silently ignore the user value.

_Maybe_ the problem will be solved as part of #4.

**Comment by codeandcats** [comment]
You can determine whether it was added or not via the result of Add. Add returns True if it was added and False it it wasn't.

That said, I hear what you're saying. Returning a boolean to indicate success it not my preferred style and generally I would raise an exception. If I were redesigning it today I would simply allow for duplicates - I don't see why there couldn't be multiple nodes at the same coordinate, hence why I added issue #4. I will update #4 with how I was thinking of handling it. Feel free to share your opinion.

**Comment by codeandcats** [comment]
Closing as #4 covers this.

**Comment by ForNeVeR** [comment]
> Add returns True if it was added and False it it wasn't.

Oh, my bad - I haven't checked the type of `Add` method. Now it makes sense, I don't think that's such a big issue. Thank you.
