### ISSUE TITLE
Add TypeMath for basic types

### ISSUE THREAD

**Issue by ForNeVeR** [codeandcats/KdTree#8]
I was surprized by lack of default `DoubleMath` implementation. Maybe it should be added and registered by default, and _maybe_ we need some another generic way to define instances for all the standard number types without duplicating the code too much.

**Comment by codeandcats** [comment]
Just merged in [PR-11](https://github.com/codeandcats/KdTree/pull/11) which added support for Double Math.

@ForNeVeR If you have any ideas on how to more easily support other types that improves on the existing method I'd been interested for sure.

For now though I'm going to close this issue.

**Comment by ForNeVeR** [comment]
@codeandcats I'll think about it; thanks! The `DoubleMath` implementation looks good.
