### ISSUE TITLE
Is there any way to traverse KdTree?

### ISSUE THREAD

**Issue by zry656565** [codeandcats/KdTree#9]
I found that `root` in `KdTree`'s declaration is **private** and `leftChild` and `rightChild` is **internal** in `KdTreeNode`. It seems that there may be no way to traverse KdTree for now.

**Comment by codeandcats** [comment]
You're right, it appears there is no way to iterate over the tree currently.

I should have some free time this weekend so I'll add it in then. :)

**Comment by zry656565** [comment]
Thanks! :beer:

**Comment by codeandcats** [comment]
Fixed in version 1.1.0.

KdTree now implements generic IEnumerable which yields each node in the tree.

**Comment by zry656565** [comment]
Good job!
